name: CI

on:
  push:
    tags:
    - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@master
        with:
          ref: master
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          version: ${{ matrix.node_version }}
      - name: Setup hexo
        env:
          ACTION_DEPLOY_KEY: ${{ secrets.ACTION_DEPLOY_KEY }}
          USER_NAME: ${{ secrets.USER_NAME }}
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
        run: |
          mkdir -p ~/.ssh/
          echo "$ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.email "$USER_EMAIL"
          git config --global user.name "$USER_NAME"
          npm install hexo-cli -g
          npm install hexo-deployer-git  --save
          #npm install hexo --save
          npm install
      - name: Hexo deploy
        run: |
          #echo '1'
          hexo clean
          #echo '2'
          hexo g
          #echo '3'
          hexo d
      - name: Setup aliyun oss
        uses: manyuanrong/setup-ossutil@v2.0
        with:
          endpoint: ${{ secrets.OSS_END_POINT }}
          access-key-id: ${{ secrets.OSS_ACCESS_KEY_ID }}
          access-key-secret: ${{ secrets.OSS_ACCESS_KEY_SECRET }}
      - name: Deploy docs
        env:
          OSS_BUCKET_NAME: ${{ secrets.OSS_BUCKET_NAME }}
        run: |
          ossutil cp -rf ./public/ oss://$OSS_BUCKET_NAME/
          hexo d
